### ISSUE TITLE
当提交的LogGroup 的content 为空时，服务器会返回 400错误 ，并且不会回调onFailure

### ISSUE THREAD

**Issue by yiyayiya** [aliyun/aliyun-log-android-sdk#14]
当提交的LogGroup 的content 为空时，服务器会返回 400错误 ：{"errorCode":"PostBodyInvalid","errorMessage":"wrong data type"}
此时logClient.asyncPostLog 不会回调onFailure，原因是
RequestTask 201到213行那段代码有Exception 没有catch

￼

￼

2018-08-02 10:12:45.619 27035-27193/com.aliyun.sls D/OSS-Android-SDK: response:---------------------
response code : 400 for url : http://biaotest.cn-shenzhen.log.aliyuncs.com/logstores/demo/shards/lb
response body : {"errorCode":"PostBodyInvalid","errorMessage":"wrong data type"}

￼

**Comment by lygttpod** [comment]
# 所遇情况同上

* 问题：使用过程中发现上传日志很多异常情况下不会回调onFailure方法
* 影响：无法回调onFailure方法就无法针对异常信息做特殊处理，比如sts_token过期报的401错误等，要在token过期时候onFailure中做重新刷新token的操作，导致很多业务无法继续
* 原因：调试中发现RequestTask类中第200行代码没有try catch ，因为Exception而没有走onFailure方法
* 期望：修复bug，发布新版本

## 备注：bug虽小，造成的后果却很严重，望重视，尽早修复，谢谢！

![image](https://user-images.githubusercontent.com/11826777/52907922-6ad7d380-32a6-11e9-9ea7-0ad6b8402353.png)

![image](https://user-images.githubusercontent.com/11826777/52924829-62949c80-3369-11e9-95fb-82d2eabe4808.png)

**Comment by 1019272778** [comment]
fixed。可以参考最新的master分支代码
