### ISSUE TITLE
CacheManager 内部CacheTimerTask弱引用导致的空指针问题

### ISSUE THREAD

**Issue by jerryisbusy** [aliyun/aliyun-log-android-sdk#16]
CacheTimerTask：
if (mWeakCacheManager.get().mClient.getPolicy() == ClientConfiguration.NetworkPolicy.WIFI_ONLY && activeNetwork.getType() == ConnectivityManager.TYPE_WIFI) {
                    shouldPost = true;
                } else if (mWeakCacheManager.get().mClient.getPolicy() == ClientConfiguration.NetworkPolicy.WWAN_OR_WIFI) {
                    shouldPost = true;
                }

mWeakCacheManager.get()有可能返回空指针的。
目前已经在多台手机上，发生了数十次了。
什么时候能修复下？

**Comment by jerryisbusy** [comment]
我已经提交了工单了。希望有人能快点修复。

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
