### ISSUE TITLE
上传返回400

### ISSUE THREAD

**Issue by changjiashuai** [aliyun/aliyun-log-android-sdk#17]
10-24 15:56:36.941 3448-3865/in.togetu.video D/OSS-Android-SDK: [, , 0]:response:---------------------
    response code : 400 for url : http://togetu.ap-south-1.log.aliyuncs.com/logstores/log-android/shards/lb
    response body : {"errorCode":"ParameterInvalid","errorMessage":"http extend authorization : ---initValue--- pair is invalid"}
    
    responseHeader [access-control-allow-origin]: *
    responseHeader [connection]: close
    responseHeader [content-length]: 110
    responseHeader [content-type]: application/json
    responseHeader [date]: Thu, 25 Oct 2018 06:27:45 GMT
    responseHeader [server]: nginx
    responseHeader [x-log-requestid]: 5BD1626149F48530568A8B3B

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
