### ISSUE TITLE
偶发android.database.sqlite.SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by piitw** [aliyun/aliyun-log-android-sdk#23]
1 android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
--
2 android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
3 android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
4 android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
5 android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
6 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:134)
7 org.greenrobot.greendao.AbstractDao.loadAllFromCursor(SourceFile:453)
8 org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(SourceFile:203)
9 org.greenrobot.greendao.InternalQueryDaoAccess.a(SourceFile:37)
10 org.greenrobot.greendao.query.Query.c(SourceFile:89)
11 com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SourceFile:84)
12 com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(SourceFile:85)
13 com.aliyun.sls.android.sdk.CacheManager.access$100(SourceFile:19)
14 com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(SourceFile:68)
15 java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by lgw666** [comment]
+1

**Comment by cqllang** [comment]
大量触发：


android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
--
 android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
 android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
 org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:453)
 org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
 org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
 org.greenrobot.greendao.query.Query.list(Query.java:89)
 com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SLSDatabaseManager.java:81)
com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(CacheManager.java:85)
 com.aliyun.sls.android.sdk.CacheManager.access$100(CacheManager.java:19)
 com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:68)
 java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
