### ISSUE TITLE
更新2.1出现NoClassDefFoundError

### ISSUE THREAD

**Issue by piitw** [aliyun/aliyun-log-android-sdk#24]
使用2.1jar
初始化SLSDatabaseManager.getInstance().setupDB(getApplicationContext());
出现 
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aliyun/sls/android/sdk/DaoMaster$DevOpenHelper;
        at com.aliyun.sls.android.sdk.SLSDatabaseManager.setupDB(SourceFile:51)

是使用方式有问题吗

**Comment by L1uj1awe1** [comment]
遇到同样的问题。  Caused by: java.lang.NoClassDefFoundError: com.aliyun.sls.android.sdk.DaoMaster$DevOpenHelper

**Comment by L1uj1awe1** [comment]
> 使用2.1jar
> 初始化SLSDatabaseManager.getInstance().setupDB(getApplicationContext());
> 出现
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aliyun/sls/android/sdk/DaoMaster$DevOpenHelper;
> at com.aliyun.sls.android.sdk.SLSDatabaseManager.setupDB(SourceFile:51)
> 
> 是使用方式有问题吗

需要另外引用 FastJson 、GreenDAO

**Comment by piitw** [comment]
> > 使用2.1jar
> > 初始化SLSDatabaseManager.getInstance().setupDB(getApplicationContext());
> > 出现
> > java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aliyun/sls/android/sdk/DaoMaster$DevOpenHelper;
> > at com.aliyun.sls.android.sdk.SLSDatabaseManager.setupDB(SourceFile:51)
> > 是使用方式有问题吗
> 
> 需要另外引用 FastJson 、GreenDAO

已经解决，感谢！
