### ISSUE TITLE
后台模式下偶发 android.database.CursorWindowAllocationException

### ISSUE THREAD

**Issue by spwCoding** [aliyun/aliyun-log-android-sdk#25]
都是在子进程中发生异常：
android.database.CursorWindowAllocationException
Cursor window allocation of 2048 kb failed.

Log 堆栈

android.database.CursorWindow.<init>(CursorWindow.java:110)
--
 android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
 org.greenrobot.greendao.AbstractDao.loadAllFromCursor(SourceFile:453)
org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(SourceFile:203)
org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(SourceFile:37)
 org.greenrobot.greendao.query.Query.list(SourceFile:89)
com.aliyun.sls.android.sdk.k.b(SourceFile:84)
 com.aliyun.sls.android.sdk.b.c(SourceFile:85)
com.aliyun.sls.android.sdk.b.b(SourceFile:19)
 com.aliyun.sls.android.sdk.b$a.run(SourceFile:68)
java.util.TimerThread.mainLoop(Timer.java:555)
 java.util.TimerThread.run(Timer.java:505)

**Comment by cqllang** [comment]
同样的问题
`

1 android.database.CursorWindow.<init>(CursorWindow.java:108)
--
2 android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:201)
3 android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
4 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
5 org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:453)
6 org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
7 org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
8 org.greenrobot.greendao.query.Query.list(Query.java:89)
9 com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SLSDatabaseManager.java:81)
10 com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(CacheManager.java:85)
11 com.aliyun.sls.android.sdk.CacheManager.access$100(CacheManager.java:19)
12 com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:68)
13 java.util.Timer$TimerImpl.run(Timer.java:284)
`
会导致程序退出。
请问下有解决办法么？

**Comment by Xiang0112** [comment]
我也出现了，请问你怎么解决的

**Comment by spwCoding** [comment]
> 我也出现了，请问你怎么解决的
看一下alilog sdk源码，初始化时内部默认缓存日志开始后，会默认创建一个timer,这个timer如果在其它子进程中调用时，系统为子进程分配的内存不够就会抛这个问题。
缓存日志开关是这个类 ClientConfiguration clientConfiguration;  clientConfiguration.setCachable(false), 看下源代码，自已实现一下缓存日志上传的流程，（其实就是保证在主进程中上传缓存日志，希望能帮到你）

**Comment by Xiang0112** [comment]
我现在setCachable设置的true，难道是因为阿里云那边缓存的过多导致？那我现在设置不缓存是不是就不会出现了。

**Comment by Xiang0112** [comment]
我这边逻辑是这样的：我会每分钟检测本地数据库看是否有日志未上传，如果检测到就立即上传到阿里云，但是有可能是网络问题，一分钟都没有上传上去，导致过了一分钟又回继续上传，当数据比较多的时候，就会出现这种异常

**Comment by spwCoding** [comment]
> 我这边逻辑是这样的：我会每分钟检测本地数据库看是否有日志未上传，如果检测到就立即上传到阿里云，但是有可能是网络问题，一分钟都没有上传上去，导致过了一分钟又回继续上传，当数据比较多的时候，就会出现这种异常

建议看一下源码吧？
CacheManager 源码里的这个类
 private void fetchDataFromDBAndPost() {
        List<LogEntity> list = SLSDatabaseManager.getInstance().queryRecordFromDB();
        Iterator var2 = list.iterator();

        while(var2.hasNext()) {
            final LogEntity item = (LogEntity)var2.next();
            String clientEndPoint = this.mClient.GetEndPoint();
            if (clientEndPoint.equals(item.getEndPoint())) {
                try {
                    PostCachedLogRequest request = new PostCachedLogRequest(item.getProject(), item.getStore(), item.getJsonString());
                    this.mClient.asyncPostCachedLog(request, new CompletedCallback<PostCachedLogRequest, PostCachedLogResult>() {
                        public void onSuccess(PostCachedLogRequest request, PostCachedLogResult result) {
                            SLSDatabaseManager.getInstance().deleteRecordFromDB(item);
                        }

                        public void onFailure(PostCachedLogRequest request, LogException exception) {
                            SLSLog.logError("send cached log failed");
                        }
                    });
                } catch (LogException var7) {
                    var7.printStackTrace();
                }
            }
        }

    }


你的异常是在子进程报的，还是主进程报的？

**Comment by Xiang0112** [comment]
子线程
我是这样上传日志的：
   /* 创建logGroup */
        LogGroup logGroup = new LogGroup("DATA_SAVE", TextUtils.isEmpty(source_ip) ? " no ip " : source_ip);
        /* 存入一条log */
        Log log = new Log();

        log.PutContent("id",userId);
        log.PutContent("code",versionCode+"");
        log.PutContent("uid",uid+"");
        log.PutContent("name",name);
        log.PutContent("msg",msg);
        log.PutContent("time",ToolFormat.parseTimestamp(new Date()));

        logGroup.PutLog(log);

        try {
            PostLogRequest request = new PostLogRequest(project, logStore, logGroup);
            logClient.asyncPostLog(request, call);
        }catch (Exception e){

        }

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
