### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Wanghehuang** [aliyun/aliyun-log-android-sdk#26]
crash log:

java.lang.NullPointerException: Attempt to read from field 'com.aliyun.sls.android.sdk.LOGClient com.aliyun.sls.android.sdk.CacheManager.mClient' on a null object reference
	at com.aliyun.sls.android.sdk.CacheManager.access$000(CacheManager.java:19)
	at com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:61)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

 a low probability of random events.

**Comment by chaolee50** [comment]
你好，用的是最新的代码吗

**Comment by Wanghehuang** [comment]
是的，我有把代码拉下来看。应该是有概率出现的

**Comment by chaolee50** [comment]
> 是的，我有把代码拉下来看。应该是有概率出现的
最近的更新，你看一下，应该可以解决这个问题

**Comment by chaolee50** [comment]
> 是的，我有把代码拉下来看。应该是有概率出现的

最近的更新，你看一下，应该可以解决这个问题

**Comment by Wanghehuang** [comment]
OK。辛苦了！

**Comment by Wanghehuang** [comment]
请问下maven有上传新版本么？我现在用的是2.0.0(com.aliyun.openservices:aliyun-log-android-sdk:2.0.0)版本，好像没有更新到你最新代码

**Comment by chaolee50** [comment]
还没有上传新版本，可以参考[源码编译](https://github.com/aliyun/aliyun-log-android-sdk/blob/master/README-CN.md)
