### ISSUE TITLE
android.os.DeadSystemException

### ISSUE THREAD

**Issue by ValuesFeng** [aliyun/aliyun-log-android-sdk#28]
1 java.lang.RuntimeException:android.os.DeadSystemException
--
2 android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:768)
3 ......
4 android.os.DeadSystemException:
5 android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:768)
6 com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.void run()(CacheManager.java:52)
7 java.util.TimerThread.mainLoop(Timer.java:555)
8 java.util.TimerThread.run(Timer.java:505)

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
