### ISSUE TITLE
Cursor window allocation of 2048 kb failed.  com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SLSDatabaseManager.java)

### ISSUE THREAD

**Issue by Xiang0112** [aliyun/aliyun-log-android-sdk#33]
我本地的逻辑是这样的：我会每分钟检测本地数据库看是否有日志未上传，如果检测到就立即上传到阿里云，但是有可能是网络问题，一分钟都没有上传上去，导致过了一分钟又回继续上传，当数据比较多的时候，就会出现这种异常，请问这种问题怎么解决
出错堆栈

1	android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
2	android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
3	android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
4	android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
5	android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
6	android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
7	org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java)
8	org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java)
9	org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java)
10	org.greenrobot.greendao.query.Query.list(Query.java)
11	com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SLSDatabaseManager.java)
12	com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(CacheManager.java)
13	com.aliyun.sls.android.sdk.CacheManager.access$100(CacheManager.java)
14	com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java)
15	java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
