### ISSUE TITLE
批量日志上传问题

### ISSUE THREAD

**Issue by xmuSistone** [aliyun/aliyun-log-android-sdk#37]
SLS挺好用的。但是有个问题想问下：App频发请求，想批量日志上报；SDK内部有封装好的方法不？比如一个LogGroup达到10条log的时候，再一次性上报？

**Comment by aileo2025** [comment]
@xmuSistone Hi 兄弟我这边需求跟你是一样的，你这边解决了吗。

**Comment by xmuSistone** [comment]
@devyul 我们用了HandlerThread，统一处理上报逻辑，单线程模型。业务侧调用SLS时，先把log保存至本地数据库，同时开始检查是否具备日志上报条件。HandlerThread内部日志上报条件有两条线：1. 本地log日志是否已经足够多；2. 内部轮询是否超时

**Comment by aileo2025** [comment]
> @devyul 我们用了HandlerThread，统一处理上报逻辑，单线程模型。业务侧调用SLS时，先把log保存至本地数据库，同时开始检查是否具备日志上报条件。HandlerThread内部日志上报条件有两条线：1. 本地log日志是否已经足够多；2. 内部轮询是否超时

明白了，谢谢哈😆
