### ISSUE TITLE
Android studio运行编译不了

### ISSUE THREAD

**Issue by xayo69** [aliyun/aliyun-log-android-sdk#42]
项目怎么studio编译不过去。

**Comment by chaolee50** [comment]
> 项目怎么studio编译不过去。

有什么报错吗，可以加我们的群看一下
http://t.cn/AiRpol8C

**Comment by xayo69** [comment]
> > 项目怎么studio编译不过去。
> 
> 有什么报错吗，可以加我们的群看一下
> http://t.cn/AiRpol8C

已经好了，需要导入ndk包

**Comment by xayo69** [comment]
// 设置主题
config.setTopic("test_topic");
// 设置tag信息，此tag会附加在每条日志上
config.addTag("test", "test_topic");
这个setTopic是随便写，还是固定是这个值？
有没有详细点的文档说明？

**Comment by chaolee50** [comment]
> // 设置主题
> config.setTopic("test_topic");
> // 设置tag信息，此tag会附加在每条日志上
> config.addTag("test", "test_topic");
> 这个setTopic是随便写，还是固定是这个值？
> 有没有详细点的文档说明？

自定义的，就相当给日志加个标签
https://help.aliyun.com/document_detail/48871.html
https://help.aliyun.com/document_detail/92264.html
