### ISSUE TITLE
可以再往下支持到Android5.1吗？

### ISSUE THREAD

**Issue by ooyeah** [aliyun/aliyun-log-android-sdk#46]

**Comment by chiclaim** [comment]
我们公司的客户全是 android5.0 的系统， 2B 的业务都是老POS机

**Comment by chaolee50** [comment]
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.3.0'

**Comment by ooyeah** [comment]
👍！效率杠杠的！
