### ISSUE TITLE
能否对外曝露简单的POST请求接口，封装好的SDK并不一定适用于每个业务

### ISSUE THREAD

**Issue by 765947965** [aliyun/aliyun-log-android-sdk#48]
能否对外曝露简单的POST请求接口，封装好的SDK并不一定适用于每个业务

**Comment by chaolee50** [comment]
参考这个文档最下，是否满足
https://help.aliyun.com/document_detail/31752.html

**Comment by 765947965** [comment]
收到，感谢!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aliyun/aliyun-log-android-sdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 下午3:55
收件人:&nbsp;"aliyun/aliyun-log-android-sdk"<aliyun-log-android-sdk@noreply.github.com&gt;;
抄送:&nbsp;"谢文良"<765947965@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aliyun/aliyun-log-android-sdk] 能否对外曝露简单的POST请求接口，封装好的SDK并不一定适用于每个业务 (#48)





 
参考这个文档最下，是否满足
 https://help.aliyun.com/document_detail/31752.html

**Comment by 765947965** [comment]
已解决
