### ISSUE TITLE
minSdkVersion 的疑问

### ISSUE THREAD

**Issue by nichbar** [aliyun/aliyun-log-android-sdk#49]
项目里的 minSdkVersion 是 19，demo 里改为 16 以后也能编译运行，能否降低 minSdkVersion 提高兼容度呢？

(PS: 我们项目的 minSdkVersion 是 16)

**Comment by chaolee50** [comment]
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'

 您试试这个
