### ISSUE TITLE
麻烦提供armeabi的动态链接库so, 以增强此日志库的上层适应性

### ISSUE THREAD

**Issue by matrixxun** [aliyun/aliyun-log-android-sdk#50]
![image](https://user-images.githubusercontent.com/2074894/98090414-f3553800-1ebe-11eb-9ef4-85177bcda41e.png)
我们的业务App为了体积尽可能小, 选择只保留ndk {abiFilters  "armeabi" }, 所以麻烦提供下armeabi的so库, 多谢.

**Comment by chaolee50** [comment]
新版的NDK不支持armeabi了，用armeabi-v7a呢

**Comment by matrixxun** [comment]
> 新版的NDK不支持armeabi了，用armeabi-v7a呢

我们app必须要使用支付宝的小程序, 他们只提供了armeabi, 所以...

**Comment by chaolee50** [comment]
您试下这个

[aliyun-log-android-sdk-release.aar](https://github.com/aliyun/aliyun-log-android-sdk/releases/download/release_2.4.1-beta/aliyun-log-android-sdk-release.aar)
