### ISSUE TITLE
能否支持动态更新LogProducerConfig

### ISSUE THREAD

**Issue by xiongwei-git** [aliyun/aliyun-log-android-sdk#52]
目前如果动态更新LogProducerConfig,并且重新实例化LogProducerClient,会导致崩溃.Android和iOS都是如此.
如果destroyClient,再创建,有可能造成日志丢失

**Comment by chaolee50** [comment]
> 目前如果动态更新LogProducerConfig,并且重新实例化LogProducerClient,会导致崩溃.Android和iOS都是如此.
> 如果destroyClient,再创建,有可能造成日志丢失

为什么需要动态更新，需求是什么呢

**Comment by chiclaim** [comment]
@chaolee50 因为客户端所有关于配置都是服务端返回的（endpoint，project，logstore，accessKeyId，accessKeySecret，securityToken），这样做的目的可以让服务端动态指定存在阿里云的那个 project,logstore 等，更加灵活一点。因为 app 可能很多，现在是按照项目分，如果以后打算按照平台（android/ios）来划分存储的地方，那么就必须升级包才能做到。但是 sdk 中的 resetSecurityToken 方法，只支持 accessKeyId，accessKeySecret，securityToken 参数，不能指定 endpoint，project，logstore 等参数。

**Comment by xiongwei-git** [comment]
@chaolee50 之前我是有一些动态信息想通过 LogProducerConfig.addTag的方式配置进去，比如userId、deviceId等。
现在我改为了把这些信息动态的放到log中了，通过log.putContent上报动态信息。

另外我认为 @chiclaim 的需求确实也有可能存在，比如App支持切换环境，不同的环境对应上报log的logstore又不一样。这时候就需要动态切换配置信息了。

**Comment by cnbleu** [comment]
2.6.0 版本已经支持[动态配置](https://github.com/aliyun/aliyun-log-android-sdk#%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE)

@chiclaim @xiongwei-git
