### ISSUE TITLE
新版本SDK 使用了 support 包，导致 androidx 项目用不了

### ISSUE THREAD

**Issue by chiclaim** [aliyun/aliyun-log-android-sdk#53]
新版本SDK 使用了 support 包，导致 androidx 项目用不了；
能否将每个新版本 SDK 更新的内容列出来，类似 changelog

**Comment by chaolee50** [comment]
您好

implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.5.1'

**Comment by chaolee50** [comment]
您好，已经移除了

implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.5.1'

**Comment by chiclaim** [comment]
多谢
