### ISSUE TITLE
初始化AccessKey Secret必须放在客户端？有其他方式么？AccessKey Secret安全如何保障

### ISSUE THREAD

**Issue by yyyAndroid** [aliyun/aliyun-log-android-sdk#54]
初始化AccessKey Secret必须放在客户端？有其他方式么？AccessKey Secret安全如何保障

**Comment by chaolee50** [comment]
通过STS，搭建STS服务，
https://help.aliyun.com/document_detail/47277.html
https://help.aliyun.com/document_detail/62681.html
设置accesskeyid, accesskeysecret, securityToken
[MainActivity.java#L61](https://github.com/aliyun/aliyun-log-android-sdk/blob/b20e710c09075a93a833192543e5053fc1e4fa45/app/src/main/java/com/aliyun/sls/android/producer/test/MainActivity.java#L61)
