### ISSUE TITLE
aliyunlog版本升级

### ISSUE THREAD

**Issue by wuyinlei** [aliyun/aliyun-log-android-sdk#56]
2.1.0的版本和最新的版本使用方式不一样了？发现之前的jar包都是java写的，使用方式也和新版不一致了？

**Comment by chaolee50** [comment]
是的，可以参考README，项目中也有例子

**Comment by wuyinlei** [comment]
好的，我看下的，谢谢

**Comment by wuyinlei** [comment]
还有一个问题，就是我上报日志是1个本地的 上报也是一个-->  resultCode --> 0 ,但是我在后台日志库中看到了两个一模一样的日志，间隔是2s，请问是哪个地方的问题？需要注意什么

**Comment by chaolee50** [comment]
是同一条日志吗，有add两次吗，有几个client呢

**Comment by wuyinlei** [comment]
LogProducerConfig config = new LogProducerConfig(endpoint,project,logStore,AK,SK);
            LogProducerClient client = new LogProducerClient(config, new LogProducerCallback() {
                @Override
                public void onCall(int resultCode, String reqId, String errorMessage, int logBytes, int compressedBytes) {
                    Log.e("BaseApplication"," resultCode --> " + resultCode);
                    Log.e("BaseApplication"," errorMessage --> " + errorMessage);

                }
            });

            Log.e("BaseApplication","init--> client  " + client);
            com.aliyun.sls.android.producer.Log log = oneLog();
            client.addLog(log);

这个是测试代码，然后控制台打印也是一个，但是后台上报的是两个
![image](https://user-images.githubusercontent.com/14150120/101774419-0b0c8580-3b29-11eb-915a-5d7eb2135943.png)

而且是间隔2s.

**Comment by chaolee50** [comment]
@wuyinlei 这两个日志内容time不一样，不是一条日志的，检查下是不是生成了两条日志呢

**Comment by wuyinlei** [comment]
![image](https://user-images.githubusercontent.com/14150120/101869555-ac8fe780-3bba-11eb-997d-7511847c857a.png)
![image](https://user-images.githubusercontent.com/14150120/101869578-bade0380-3bba-11eb-9239-20dba0ccddf4.png)
我整个控制台就打印出一个time 1607666950746,对应的是两条日志的第一个日志，但是2s之后的那个日志并没有日志，不是我生成了两条日志导致。而且上报返回的onCall也是只调用了一次。

**Comment by wuyinlei** [comment]
我这边又测试了，在activity页面上报，是一个日志，有点奇怪，我这边在试下哈。辛苦
