### ISSUE TITLE
关于 Token 过期，导致日志丢失问题

### ISSUE THREAD

**Issue by chiclaim** [aliyun/aliyun-log-android-sdk#59]
流程：
1，使用 app，程序请求 sls token 信息，正常采集上传。（假设 token 过期是 2 小时）
2，2小时后，用户再次启动 app，由于 token 过期，去请求新的 token，在请求新token之前的日志，肯定会上传失败。
但是请求新 token 成功后，并不会把之前的日志一起上传。

我们把 sls token 放在本地目的，第一个主要是减少接口请求；第二个是想监控到获取 token 之前的日志。

**Comment by chaolee50** [comment]
你好，401请求只会重试一次，失败后就会把数据丢弃
建议在创建LogClient之前去获取一次STS token，这样保证启动时拿到的token就是好的

**Comment by chaolee50** [comment]
@chiclaim 你好，这个问题后面我们会改一下，加一个可以配置的参数

**Comment by chaolee50** [comment]
使用这个版本,默认不会丢弃
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.5.7'
```
https://github.com/aliyun/aliyun-log-android-sdk/blob/16d47999ac237a48f9c9f864f06c68f0887bb8b7/app/src/main/java/com/aliyun/sls/android/producer/test/MainActivity.java#L115

**Comment by chiclaim** [comment]
好的 ，我试下
