### ISSUE TITLE
使用多个数据库并开启断点续传时，日志会混乱

### ISSUE THREAD

**Issue by ghost** [aliyun/aliyun-log-android-sdk#62]
我有两个库，异常日志和埋点日志
在我断线时触发了异常，恢复网络后触发了埋点。结果异常日志发到了埋点日志库，TOPIC用的也是埋点的TOPIC

**Comment by cnbleu** [comment]
Duplicate of #68

**Comment by cnbleu** [comment]
https://github.com/aliyun/aliyun-log-android-sdk/issues/68#issuecomment-894907276

确认上上面的配置是否正确
