### ISSUE TITLE
海外应用可以接这个sdk吗，会不会有向国内发的请求？

### ISSUE THREAD

**Issue by ChrisZhao520** [aliyun/aliyun-log-android-sdk#63]
我们日志项目的地域是在国外的，因为上架google是不允许有向国内发送请求的，不知道接这个会不会有问题

**Comment by zhaoyunpeng123** [comment]
因为上架google是不允许有向国内发送请求的，不知道接这个会不会有问题

**Comment by ChrisZhao520** [comment]
问了技术可以的哦，项目在国外是不会发送到国内的，直接传输到国外的机房
