### ISSUE TITLE
resetSecurityToken次数多了之后导致oom

### ISSUE THREAD

**Issue by Key-CN** [aliyun/aliyun-log-android-sdk#66]
我们有一款桌面应用，统计发现在运行几天之后oom的概率很高
`mConfig.resetSecurityToken(sts.accessKeyId, sts.accessKeySecret, sts.securityToken)`
这一行代码导致：
`java.lang.OutOfMemoryError: Could not allocate JNI Env`
目前的规则是每隔25分钟resetSecurityToken一次
是不是应该每次都把`LogProducerClient`和`LogProducerConfig`释放掉重新创建才可以暂时解决这个问题？
sdk版本：
2.5.14，2.5.15，2.5.16

**Comment by cnbleu** [comment]
resetSecurityToken时，只是对accessKeyId、accessKey、securityToken进行了重新赋值，涉及到的内存malloc都进行了 free，请排查下业务代码中是否有内存泄露。

https://github.com/aliyun/aliyun-log-android-sdk/blob/404373d538604966c8051dcd71de7c34dd239782/aliyun_sls_android_producer/src/main/cpp/com_aliyun_sls_android_producer_LogProducerConfig.c#L114

https://github.com/aliyun/aliyun-log-c-sdk/blob/e3c4a586a68d1d5dbfb268aad51a5bf5af7e0bb9/src/log_producer_config.c#L315
