### ISSUE TITLE
java.lang.IllegalStateException:Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by lileini** [aliyun/aliyun-log-android-sdk#7]
java.lang.IllegalStateException:Fatal Exception thrown on Scheduler.Worker thread.
--
2 rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
3 ......
4 Caused by:
5 java.util.ConcurrentModificationException:
6 java.util.ArrayList$Itr.next(ArrayList.java:831)
7 com.aliyun.sls.android.sdk.model.LogGroup.LogGroupToJsonString(LogGroup.java:44)
8 com.aliyun.sls.android.sdk.LOGClient.PostLog(LOGClient.java:145)
9 com.loyo.oa.common.utils.AliLogTool$2.onCompleted(AliLogTool.java:124)
10 rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
11 rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68)
12 rx.internal.operators.EmptyObservableHolder.call(EmptyObservableHolder.java:46)
13 rx.internal.operators.EmptyObservableHolder.call(EmptyObservableHolder.java:26)
14 rx.Observable.unsafeSubscribe(Observable.java:10142)
15 rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
16 rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
17 rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
18 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
19 java.util.concurrent.FutureTask.run(FutureTask.java:237)
20 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
21 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
22 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
23 java.lang.Thread.run(Thread.java:760)

**Comment by x-zack** [comment]
+1

**Comment by 1019272778** [comment]
请问是使用了rxjava吗？

**Comment by x-zack** [comment]
是的

**Comment by HzwSunshine** [comment]
+1

**Comment by HzwSunshine** [comment]
我对此奔溃原因分析：sdk的ExecutionContext类中使用了Okhttp3，如果项目中你恰好用了okhttp和okhttp-log-interceptor，那么可能sdk中okhttp的版本和你项目中的okhttp-log-interceptor版本不一致，所以会造成奔溃。解决方式很简单，引用时排除sdk中的okhttp，然后使用项目中的okhttp版本，可解决

**Comment by x-zack** [comment]
@HzwSunshine 你解决了吗？我把项目中的okhttp3版本改为和sdk中一致的，仍然有报错

**Comment by HzwSunshine** [comment]
@GongTengFei  试试这种方式：
`api('com.aliyun.openservices:aliyun-log-android-sdk:0.4.0') {
        exclude group: "com.squareup.okhttp3"
    }`

**Comment by x-zack** [comment]
@HzwSunshine 谢谢 已经定位原因了，并不是版本冲突，确实是
SDK的代码没有考虑并发修改的问题，发现在最新的主分支代码上，
通过try catch捕获了该异常。当然，我们自己的代码处理逻辑也不合适，正常使用的情况下不会触发该异常。

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
