### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/xxx.xxx.xxx/app_libs/libsls_producer.so" not found

### ISSUE THREAD

**Issue by lejiteyu** [aliyun/aliyun-log-android-sdk#70]
1、按照阿里云 日志服务SLS 使用Maven方式集成了SDK
2、在官方文档以及github仓库都没看到so资源下载或者自己编译so文件的操作
3、报错如下： java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/com.xxx.xxx/app_libs/libsls_producer.so" not found
at java.lang.Runtime.load0(Runtime.java:938)
at java.lang.System.load(System.java:1632)
at com.aliyun.sls.android.producer.utils.SoLoader.loadLibrary(SoLoader.java:55)
4、谢谢

**Comment by cnbleu** [comment]
> 1、按照阿里云 日志服务SLS 使用Maven方式集成了SDK 2、在官方文档以及github仓库都没看到so资源下载或者自己编译so文件的操作 3、报错如下： java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/com.xxx.xxx/app_libs/libsls_producer.so" not found at java.lang.Runtime.load0(Runtime.java:938) at java.lang.System.load(System.java:1632) at com.aliyun.sls.android.producer.utils.SoLoader.loadLibrary(SoLoader.java:55) 4、谢谢

你好，请提供下 abi。

**Comment by lejiteyu** [comment]
目前使用的ＮＤK 如下
ndk {
            abiFilters 'armeabi', 'arm64-v8a'
        }

**Comment by lejiteyu** [comment]
ndk {
            abiFilters 'armeabi', 'arm64-v8a'
        }

**Comment by cnbleu** [comment]
> 目前使用的ＮＤK 如下 ndk { abiFilters 'armeabi', 'arm64-v8a' }

是否可以添加钉钉详聊，钉钉号：cnbleu

**Comment by PandaQAQ** [comment]
> > 目前使用的ＮＤK 如下 ndk { abiFilters 'armeabi', 'arm64-v8a' }
> 
> 是否可以添加钉钉详聊，钉钉号：cnbleu

有处理结果了没，也遇到了同样的问题

**Comment by cnbleu** [comment]
```
android {
    defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }
}
```

检查下 ndk abiFilters 的配置是否包含目标 abi，需要注意的是`armeabi `需要改为`armeabi-v7a`
