### ISSUE TITLE
关于Android合规化处理方案

### ISSUE THREAD

**Issue by BennyTian** [aliyun/aliyun-log-android-sdk#74]
在当前的大环境下 任何SDK 都还是要相应的出一个合规化处理方案
除非咱们的SDK完全合规 , 不涉及到任何信息收集和权限,否则就无法通过应用市场的审核.

目前的问题是: 集成之后被应用市场给打回了 说是合规化有问题,收集了设备信息等问题 

但目前还在排查是什么原因, 不确定是不是 log引起的, 但还是希望官方可以给一个说明, 方便排查问题~  感谢~~~

**Comment by cnbleu** [comment]
您好，SDK目前不涉及敏感权限的申请和敏感数据的采集。是否可以加下钉钉详聊：cnbleu
