### ISSUE TITLE
是否可以提供一个控制上传日志的方法？

### ISSUE THREAD

**Issue by xcc3641** [aliyun/aliyun-log-android-sdk#75]
关闭上传日志时，写入的日志进入本地缓存，当调用上传日志时，再回捞本地缓存进行上传。

**Comment by cnbleu** [comment]
您好，SDK目前已经支持该能力，可参考这个配置：https://github.com/aliyun/aliyun-log-android-sdk/blob/c763e76aa66d95aaddf03451492a9d7a20302911/app/src/main/java/com/aliyun/sls/android/producer/example/example/producer/ProducerExample.java#L104

**Comment by xcc3641** [comment]
可能跟我表达的意思不太一样。SDK 开始 log 的时候就会尝试进行上传，这个上传逻辑不可控制。

期望的是 SDK 提供主动上传的方法。
