### ISSUE TITLE
阿里云日志丢失

### ISSUE THREAD

**Issue by BananaHuo** [aliyun/aliyun-log-android-sdk#76]
依赖版本；com.aliyun.openservices:aliyun-log-android-sdk:2.5.13

**Comment by BananaHuo** [comment]
> 依赖版本；com.aliyun.openservices:aliyun-log-android-sdk:2.5.13

用户首次打开APP延迟初始化，首次登陆消息导致大概5%左右的线上用户没有记录日志。

**Comment by cnbleu** [comment]
> > 依赖版本；com.aliyun.openservices:aliyun-log-android-sdk:2.5.13
> 
> 用户首次打开APP延迟初始化，首次登陆消息导致大概5%左右的线上用户没有记录日志。

SDK上报日志前需要先完成SDK的初始化。

**Comment by LewinJun** [comment]
> > 依赖版本；com.aliyun.openservices:aliyun-log-android-sdk:2.5.13
> 
> 用户首次打开APP延迟初始化，首次登陆消息导致大概5%左右的线上用户没有记录日志。

我也遇到了，有后端API日志，app的日志偶尔会丢失那半个小时左右时间段

**Comment by cnbleu** [comment]
> 

你好，也是SDK延迟初始化导致的吗？是否可以贴一下SDK的初始化代码？

**Comment by cnbleu** [comment]
很久没有反馈，先关闭，后续有问题再reopen
