### ISSUE TITLE
com.aliyun.sls.android.producer.LogProducerException: Can not create log producer

### ISSUE THREAD

**Issue by Ryan-Shz** [aliyun/aliyun-log-android-sdk#77]
![image](https://user-images.githubusercontent.com/12422273/172359193-865e52a1-2fba-4557-9429-7a4c453f134a.png)

无法创建LogProducerClient，抛出： `com.aliyun.sls.android.producer.LogProducerException: Can not create log producer` 异常。

创建代码如下：
```
new LogProducerClient(config, (resultCode, reqId, errorMessage, logBytes, compressedBytes) -> {
                android.util.Log.d("LogProducerCallback", String.format("%s %s %s %s %s",
                        LogProducerResult.fromInt(resultCode), reqId, errorMessage, logBytes, compressedBytes));
            });
```

SDK版本为 `    implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.6.2'` 

请问会是什么原因？

**Comment by cnbleu** [comment]
> 

您好，SDK初始化时LogProducerConfig的配置是否可以发下？
