### ISSUE TITLE
按照案例引用，打包app后，运行不起来

### ISSUE THREAD

**Issue by soeluc** [aliyun/aliyun-log-android-sdk#78]
09-09 05:54:39.601  3698  3698 E DartMessenger: java.lang.ClassNotFoundException: Didn't find class "com.aliyun.sls.android.producer.LogProducerHttpTool" on path: DexPathList[[zip file "/data/app/com.soe.z9-Ey4QlFBTV3sQuDN-adp0qw==/base.apk"],nativeLibraryDirectories=[/data/app/com.soe.z9-Ey4QlFBTV3sQuDN-adp0qw==/lib/arm64, /data/app/com.soe.z9-Ey4QlFBTV3sQuDN-adp0qw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

**Comment by cnbleu** [comment]
您好，问题已经解决了？检查下项目工程是否开启了混淆配置。

**Comment by soeluc** [comment]
问题已经解决    minifyEnabled  设置成 true 引起的
   buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
           // minifyEnabled true
            // useProguard true
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            signingConfig signingConfigs.release
           // minifyEnabled true
        }
    }
