### ISSUE TITLE
安卓端调用log.setLogTime无效。 

### ISSUE THREAD

**Issue by WoKee** [aliyun/aliyun-log-android-sdk#84]
组装日志时，手动调用log.setLogTime()，后台查看上传时间没有按照预期时间生成。

    /**
     * This method will be removed in future version.
     * Set the __time__ field. Do not call this method for set __time__ field, this may case data lost.
     *
     * @param logTime time in second
     */
    @Deprecated
    public void setLogTime(long logTime) {
        this.logTime = logTime;
    }

**Comment by cnbleu** [comment]
setLogTime这个方法已经置为Deprecated，未来会移除掉。不建议调用该方法，SDK内部会自动对logTime进行校正。

**Comment by shaobin0604** [comment]
@cnbleu 遇到一个相关的问题，请关注下呢 #94
