### ISSUE TITLE
native层出现崩溃

### ISSUE THREAD

**Issue by HelloFish-2016** [aliyun/aliyun-log-android-sdk#87]
03-02 14:25:40.144 F/(21828): java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
03-02 14:25:40.144 F/(21828): java_vm_ext.cc:570]     in call to GetStringUTFChars
03-02 14:25:40.144 F/(21828): java_vm_ext.cc:570]     from int com.aliyun.sls.android.producer.LogProducerClient.log_producer_client_add_log_with_len(long, long, int, java.lang.String[], java.lang.String[], int)

但是我看addlog源码里这里面都有判null的
 int i = 0;
        for (Map.Entry<String, String> entry : contents.entrySet()) {
            String key = entry.getKey();
            key = key == null ? "" : key;
            keyArray[i] = key;

            String value = entry.getValue();
            value = value == null ? "" : value;
            valueArray[i] = value;

            i++;
        }
麻烦看下是啥情况
使用的sdk版本是2.6.2

**Comment by cnbleu** [comment]
> 

升级到 2.6.11 版本
