### ISSUE TITLE
最新的2.6.11版本，断网后断网过程中收集的日志恢复网络后也上传不了，已经被丢弃了。

### ISSUE THREAD

**Issue by lijionghui** [aliyun/aliyun-log-android-sdk#91]
断网过程中LogProducerCallback会回调错误码LOG_PRODUCER_SEND_DISCARD_ERROR，LOG_PRODUCER_DROP_ERROR，之后再恢复网络日志已经丢失了。

**Comment by cnbleu** [comment]
> 断网过程中LogProducerCallback会回调错误码LOG_PRODUCER_SEND_DISCARD_ERROR，LOG_PRODUCER_DROP_ERROR，之后再恢复网络日志已经丢失了。

@lijionghui 出现`LOG_PRODUCER_SEND_DISCARD_ERROR `这个错误码，可能是缓存已经写满了导致的。可以贴一下你的 SDK 初始化配置吗？

**Comment by lijionghui** [comment]
<img width="492" alt="image" src="https://github.com/aliyun/aliyun-log-android-sdk/assets/17535622/6bf43ad7-d75b-411f-aa8a-240a17071e8f">
没有打完，连上网后只有几条记录上传到阿里云后台
